#!/usr/local/sbin/suid-python --virtualenv
from __future__ import print_function

from antipathy import Path
from math import floor
from openerplib import get_connection, get_records
from pwd import getpwnam
from scription import *
from time import time

import os
import sys

CONFIG = Path('%s/config/fnx.ini' % os.environ['VIRTUAL_ENV'])

try:
    settings = OrmFile(CONFIG)
except Exception:
    print('WARNING: unable to process configfile; all parameters must be specified', verbose=0)
    HOST = ''
    USER = ''
    DB = ''
    PW = ''
else:
    HOST = settings.openerp.host
    USER = settings.openerp.user
    DB = settings.openerp.db
    PW = settings.openerp.pw

@Script(
        host=('host where OpenERP instance is running', OPTION, None),
        db=('database to use', OPTION, None),
        user=('login name to use', OPTION, None),
        pw=('password for login name', OPTION, None),
        )
def main(host, db, user, pw):
    global OE
    if host:
        module.HOST = host
    if db:
        module.DB = db
    if user:
        module.USER = user
    if pw:
        module.PW = pw
    for req in ('HOST', 'USER', 'DB'):
        if not module[req]:
            raise SystemExit('%r required; use --help for more info' % req)
    if not module.PW:
        module.PW = get_response('password:')
    OE = get_connection(hostname=HOST, database=DB, login=USER, password=PW)

@Command(
        src=Spec('network location of files', ),
        dst=Spec('local path to store files', ),
        )
def sync(src, dst):
    "synchronize files between SRC and DST"
    result = Execute(
            "rsync -auv --exclude .~lock* %s %s" % (src, dst),
            password=settings.network.pw,
            pty=True,
            )
    if result.stdout:
        if result.returncode:
            echo(result.stdout, end='')
        else:
            print(result.stdout, end='')
    if result.stderr:
        error(result.stderr, end='')
    raise SystemExit(result.returncode)


@Command(
        path=Spec('location of pdfs to sort and import', type=Path),
        progress=Spec('show progress visually', FLAG),
        id=Spec('id pattern to match', OPTION, type=unicode.upper),
        max_copies=Spec('how many archival copies to keep [default: no limit]', OPTION, type=int),
        )
def c_of_a(path, progress, id, max_copies):
    '''
    copy, move, and sort source pdfs into fnxfs file structure according to
    settings found in product.prodect
    '''
    #
    # rsync -auv --exclude '.~lock*' root@192.168.2.61:/mnt/virtualxp/JRA_Docs/. /home/JRA_Docs/.
    #
    file_id = id
    if file_id:
        print('looking in %s for files matching %s' % (path, file_id))
    else:
        print('looking in %s' % (path, ))
    product = OE.get_model('product.product')
    xml_ids = dict([
        (p['xml_id'], p['id'])
        for p in get_records(
            product,
            domain=[('xml_id','!=',False)],
            fields=['id','xml_id'],
            )])
    target_paths = dict([
        (p['id'], p['c_of_a'])
        for p in product.fnxfs_get_paths(
            ids=xml_ids.values(),
            fields=['c_of_a'],
            )])
    files = path.listdir()
    if progress:
        pb = ProgressBar(len(files), message="copying %d files..." % len(files))
    for file in files:
        print()
        if progress:
            pb.tick()
        if file.ext.lower() != '.pdf':
            if not file_id:
                print('skipping non-pdf: %r' % file)
            continue
        base = cofa_primary_level.get(file[0].lower())
        if base is None:
            if not file_id:
                print('skipping invalid name: %r  (unable to find base)' % file)
            continue
        if not file[:3].isalpha() or not file[3:8].isdigit() or file[8] not in ' .':
            if not file_id:
                print('skipping invalid name: %s  (bad chars)' % file)
            continue
        sub = file[:8].upper()
        if file_id and file_id not in sub:
            continue
        elif file_id:
            print('processing %s' % file)
        id = xml_ids.get(sub)
        if id is None:
            error('product %r does not exist in OpenERP' % (sub, ))
            continue
        target_path = Path(target_paths[id])
        if not target_path.exists():
            print('creating folder %s' % target_path)
            target_path.mkdir()
            target_path.chown(*OPENERP_IDS)
            target_path.chmod(0775)
        file = file.replace('/','%2f')
        target = target_path/file.base.upper() + file.ext.lower()
        source = path/file
        print('copying %s to %s' % (source, target), verbose=2)
        options = ('--force', '-v')
        if max_copies:
            options += ('--max-copies', '%s' % max_copies)
        _run('cp', source, target, *options)


fnx_root = Path('%s/var/openerp/fnxfs/' % os.environ['VIRTUAL_ENV'])
doc_root = Path('Documents')
sds_root = doc_root/'Safety Data Sheets'
cofa_root = doc_root/'Certificates of Analysis'

cofa_primary_level = {
        'a': cofa_root/'ABC',
        'b': cofa_root/'ABC',
        'c': cofa_root/'ABC',
        'd': cofa_root/'DEF',
        'e': cofa_root/'DEF',
        'f': cofa_root/'DEF',
        'g': cofa_root/'GHIJ',
        'h': cofa_root/'GHIJ',
        'i': cofa_root/'GHIJ',
        'j': cofa_root/'GHIJ',
        'k': cofa_root/'KLM',
        'l': cofa_root/'KLM',
        'm': cofa_root/'KLM',
        'n': cofa_root/'NOP',
        'o': cofa_root/'NOP',
        'p': cofa_root/'NOP',
        'q': cofa_root/'QRS',
        'r': cofa_root/'QRS',
        's': cofa_root/'QRS',
        't': cofa_root/'TUV',
        'u': cofa_root/'TUV',
        'v': cofa_root/'TUV',
        'w': cofa_root/'WXYZ',
        'x': cofa_root/'WXYZ',
        'y': cofa_root/'WXYZ',
        'z': cofa_root/'WXYZ',
        }

OPENERP_IDS = getpwnam('openerp')[2:4]

#-----------------
# private commands
#-----------------

def _run(*command):
    command = list(command)
    params = ['/usr/local/sbin/fnxfs', ] + command #+ ['-v'] * script_verbosity
    print(' '.join(params), end='\n\n')
    try:
        exc = None
        dst = stdout
        attempt = Execute(params, pty=True, timeout=60)
        returncode = attempt.returncode
    except ExecuteError:
        exc = sys.exc_info()[1]
        dst = stderr
        attempt = exc.process
        returncode = -1
        print(exc, 'output from command:', sep='\n', file=stderr)
    if attempt.stdout:
        print(attempt.stdout, file=dst)
    if attempt.stderr:
        print(attempt.stderr, file=stderr)
        raise SystemExit(returncode)

class ProgressBar(object):
    symbols = '\\|/-'
    def __init__(yo, finalcount, block_char='.', message=None):
        yo.instant = time()
        yo.symbol_index = 0
        yo.current_count = 0
        yo.finalcount = finalcount
        yo.blockcount = 0
        yo.block = block_char
        yo.f = sys.stdout
        if not yo.finalcount:
            return
        if message is not None:
            yo.f.write('\n\n%s\n' % message)
        yo.f.write('\n-------------------- % Progress ---------------- 1\n')
        yo.f.write('    1    2    3    4    5    6    7    8    9    0\n')
        yo.f.write('    0    0    0    0    0    0    0    0    0    0\n')
        yo.f.write('-')
    def progress(yo, count):
        yo.current_count = count
        count = min(count, yo.finalcount)
        if yo.finalcount:
            percentcomplete = int(floor(100.0*count/yo.finalcount))
        else:
            percentcomplete = 100
        blockcount = int(percentcomplete//2)
        now = time()
        if now - yo.instant > 0.05:
            symbol = yo.symbols[yo.symbol_index]
            yo.symbol_index += 1
            if yo.symbol_index >= len(yo.symbols):
                yo.symbol_index = 0
            yo.f.write('' + symbol)
            yo.f.flush()
            yo.instant = now
        if blockcount <= yo.blockcount:
            return
        yo.f.write('')
        for i in range(yo.blockcount, blockcount):
            yo.f.write(yo.block)
        yo.f.write(yo.symbols[yo.symbol_index])
        yo.f.flush()
        yo.blockcount = blockcount
        if percentcomplete == 100:
            yo.f.write('\n')
            yo.f.flush()
    def tick(yo):
        yo.current_count += 1
        yo.progress(yo.current_count)

Run()
