#!/usr/bin/env python2.7

from itertools import groupby
from math import ceil
from scription.api import *
from VSS.address import PostalCode, NameCase, BsnsCase, AddrCase, normalize_address_line, cszk
from VSS.address import us_ca_state_abbr, us_ca_state_name, ca_province_abbr, ca_province_name
from VSS.enum import Enum
from VSS.openerp import get_records
from VSS.time_machine import PropertyDict
from VSS.utils import dbf, Table, text_to_date, ProgressBar, IntEnum, contains_any, fix_phone
import openerplib

execfile('/etc/openerp/credentials')

def connect(host=HOST, database=DB, login=USER, password=PW):
    global OE
    OE = PropertyDict()
    OE.conn = openerplib.get_connection(hostname=host, database=database, login=login, password=password)
    return OE

def find_country(target):
    if not target:
        return False
    if target.lower() in ('us', 'usa', 'usoa'):
        target = 'United States'
    elif target.lower() == 'africa':
        target = 'South Africa'
    elif target.lower() == 'netherland':
        target = 'Netherlands'
    if target.lower() in OE.country:
        return OE.country[target.lower()].id
    matches = set()
    for name, rec in OE.country.items():
        if name.startswith(target):
            matches.add(rec)
        elif rec.code == target:
            matches.add(rec)
        elif target.lower() in name.lower():
            matches.add(rec)
    if len(matches) > 1:
        raise ValueError('Target: %r  Matches: %s' % (target, ', '.join([m.name for m in matches])))
    elif len(matches) == 1:
        return matches.pop().id
    else:
        return False

def find_partner(pool, target):
    pass

def find_state(state):
    if state in us_ca_state_abbr:
        state = us_ca_state_abbr[state]
    records = get_records(
            OE,
            'res.country.state',
            domain=[('name','=',NameCase(state))],
            fields=['id','name','code','country_id'],
            )
    if len(records) > 1:
        print 'state %s found as' % state
        for rec in records:
            print '   %s -> %s' % (rec.country_id.name, rec.name)
        return False, False
    if records:
        return records[0].id, records[0].country_id[0]
    return False, False


def fix_names(*names):
    result = []
    for name in names:
        result.append(name.upper())
    if len(names) == 1:
        return result[0]
    return result

def Float(value):
    try:
        return float(value)
    except ValueError:
        return False

def customer_contact(customer, name, address, city, state, postal, country, contact, phone):
    current_contacts = OE.partner_data[customer.xml_id].child_ids
    values = PropertyDict()
    if contact:
        values.name = NameCase(contact)
    else:
        values.name = BsnsCase(name)
    values.street, values.street2 = address1, address2 = AddrCase(normalize_address_line(address))
    if country == 'USA':
        country = ''
    _, city, state, postal, country = cszk('%s, %s' % (city, state), '%s  %s' % (postal, country))
    state_id, country_id = False, False
    if state:
        state_id, country_id = find_state(state)
    if not country_id:
        country_id = find_country(country)
    values.city, values.state_id, values.zip, values.country_id = city, state_id, postal.code, country_id
    values.phone = fix_phone(unicode(phone))
    values.parent_id = customer.id
    contact_id = False
    if current_contacts:
        contacts = get_records(
                OE.partner,
                ids=current_contacts,
                fields='id name street street2 city state_id zip country_id phone'.split(),
                )
        for c in contacts:
            for f in 'name street street2 city state_id zip country_id phone'.split():
                failure = False
                cf = c[f]
                vf = values[f]
                if f[-3:] == '_id' and cf:
                    cf = cf[0]
                if cf and cf != vf:
                    break
            else:
                contact_id = c.id
            if contact_id:
                break
    if not contact_id:
        values.type = 'delivery'
        values.use_parent_address = False
        contact_id = OE.partner.create(dict(values))
        current_contacts.append(contact_id)
    return contact_id


def get_item_id(model, item_code):
    res = get_records(OE, 'product.product', fields=['id'], domain=[('xml_id','=',item_code)], max_qty=1)
    if not res:
        raise ValueError('Item %s not found' % item_code)
    return res[0].id

def get_lot_no(text):
    text = text.strip(' \t\'"\n').upper()
    if ( not text
      or not text.startswith(('0', '1', '3', 'P', 'A', 'C', 'F', 'G', 'L', 'M', 'R'))
      or not 4 < len(text) < 9
      or contains_any(text, '/', ' ', '(', ')')):
        return ''
    return text

def get_item_desc(text):
    try:
        item_code, desc = text.strip(' \t\'"\n').split(' ', 1)
    except ValueError:
        return '', ''
    if not (item_code[:3].isalpha() and item_code[3:].isdigit() and len(item_code) == 8):
        return '', ''
    return item_code, desc

def measurement(user_measurement):
    "remove trailing 's', return first and last characters"
    um = user_measurement.lower().rstrip('s')
    if len(um) > 1:
        um = um[::(len(um)-1)]
    if um == 'pc':
        um = 'ea'
    elif um == 'mt':
        um = 'lb'
    elif um in ('lg', 'jg'):
        um = 'kg'
    return um

def regulatory(value):
    "allowed values: n/a, cleared, rejected"
    value = value.lower().replace('.','').replace(';','').replace(' ','')
    if value in ('n/a', 'n/', 'na/', '/na'):
        value = 'na'
    elif value in ('hold', ):
        value = 'held'
    elif value in ('clearecd', ):
        value = 'cleared'
    if value not in ('', 'na', 'cleared', 'held', 'rejected'):
        raise ValueError('unknown regulatory value: %r' % value)
    return (False, value)[bool(value)]

@Command(
    )
def purchasing_lots(file_name):
    """Imports Purchasing into product.lots and wholeherb_integration.product_lot

    example file name: Purchasing_Database_Table1.dbf

    """
    Field = IntEnum('Purchasing_Field', (
            'match_preship', 'risk_factor', 'pack', 'qty_recd', 'qty_recd_uom', 'lot', 'lot_ltr', 'proj_fob_cost',
            'proj_clearance', 'supplier_name', 'item_code', 'desc', 'act_cost', 'cost', 'on_order', 'on_order_uom',
            'act_fob_cost', 'qty_avail', 'status', 'etd_0son', 'terms', 'po_no', 'vessel', 'date', 'usda', 'fda',
            'customs', 'c_of_a', 'preship_lot', 'preship_status', 'c_of_o', 's_comment', 'pr_comment', 'i_f', 'cus',
            'misc', 'date_recd', 'supplier_no',
            ))
    as_is = (
            'risk_factor',  'on_order', 'status', 'etd_0son', 'terms', 'c_of_a', 's_comment', 'pr_comment',
            )
    floats = (
            'pack', 'cost', 'proj_clearance', 'act_fob_cost', 'act_cost', 'i_f', 'cus', 'misc',
            )
    if len(Field) != 38:
        raise ValueError('Field should have 29 members, but actually has %d members' % len(Field))
    if len(as_is) != 8:
        raise ValueError('as_is should have 23 members, but actually has %d members' % len(as_is))
    print 'connecting to OE...'
    OE = connect()
    lots_model = OE.conn.get_model('wholeherb_integration.product_lot')
    po_model = OE.conn.get_model('wholeherb_integration.purchase_order')
    print 'getting Unit of Measure records...'
    oe_uom = PropertyDict((r.name, r) for r in get_records(OE, 'product.uom'))
    print 'getting Partner records (this will take a bit)...'
    oe_suppliers = PropertyDict(('%s-%s' % (r.module, r.xml_id), r) for r in get_records(
        OE,
        model='res.partner',
        domain=[('module','in',['posm','vnms'])],
        fields=['id','name','xml_id','module'],
        ))
    print 'getting Product records (this will take even longer)...'
    oe_products = PropertyDict((r.xml_id, r) for r in get_records(
        OE,
        model='product.product',
        fields=['id', 'xml_id', 'name'],
        ))
    print 'getting Country records...'
    global oe_country
    oe_country = PropertyDict((r.name.lower(), r) for r in get_records(OE, 'res.country'))
    print 'getting purchases...'
    oe_purchases = PropertyDict((r.purchase_order.lower(), r) for r in get_records(OE, 'wholeherb_integration.purchase_order'))
    #for po_num, po in oe_purchases.items():
    #    print po.lot_ids
    #    po.lot_ids = [l.id for l in po.lot_ids]
    oe_purchases_by_id = dict((p.id, p) for p in oe_purchases.values())
    print 'getting lots...'
    oe_lots = PropertyDict((l.lot_no.lower(), l) for l in get_records(OE, 'wholeherb_integration.product_lot'))
    oe_lots_by_id = dict((l.id, l) for l in oe_lots.values())
    table = Table(file_name)
    with table:
        def index(rec):
            if isinstance(rec, dbf.Record) and dbf.recno(rec) == 0:
                return dbf.DoNotIndex
            return rec[Field.po_no], rec[Field.item_code]
        order = table.create_index(index)
        print 'processing %s...' % file_name
        pb = ProgressBar(len(order))
        for po, products in groupby(dbf.Templates(order), index):
            lot_ids = set()
            for lot in products:
                pb.tick()
                for fld in Field:
                    lot[fld] = lot[fld].strip('"\'')
                if not lot[Field.lot]:
                    continue
                values = PropertyDict()
                values.lot_no = ''.join(fix_names(lot[Field.lot], lot[Field.lot_ltr]))
                product = lot[Field.item_code]
                if product not in oe_products:
                    continue
                values.product_id = oe_products[product].id
                values.match_preship = lot[Field.match_preship].lower() == 'yes'
                for field in floats:
                    values[field] = Float(lot[Field[field]])
                for field, offset in (
                        ('on_order_uom_id', Field.on_order_uom),
                        ('qty_recd_uom_id', Field.qty_recd_uom),
                        ):
                    uom = measurement(lot[offset])
                    if uom:
                        try:
                            values[field] = oe_uom[uom].id
                        except Exception, exc:
                            print 'Lot %s: %s' % (values.lot_no, exc.message)
                try:
                    values.qty_recd = int(ceil(float(lot[Field.qty_recd])))
                except ValueError:
                    values.qty_recd = False
                values.qty_remain = 0 or values.qty_recd
                for field, offset in (
                        ('expected_date', Field.date),
                        ('recd_date', Field.date_recd),
                        ):
                    try:
                        date = text_to_date(lot[offset], format='mdy') or False
                    except ValueError:
                        date = False
                    if date:
                        values[field] = unicode(date)
                qty_avail = lot[Field.qty_avail].lower()
                if qty_avail in ('all', 'some', 'none'):
                    values.qty_avail = qty_avail
                values.usda = regulatory(lot[Field.usda])
                values.fda = regulatory(lot[Field.fda])
                values.customs = regulatory(lot[Field.customs])
                if lot[Field.preship_lot] in oe_lots:
                    preship = oe_lots[lot[Field.preship_lot]]
                    values.preship_id = preship.id
                    if not preship.status and lot[Field.preship_status]:
                        lots_model.write([preship.id], {'status':unicode(lot[Field.preship_status])})
                cofo_id = find_country(oe_country, lot[Field.c_of_o])
                if cofo_id:
                    values.cofo_ids = [(6, 0, [cofo_id])]
                for offset in as_is:
                    field = lot[Field[offset]]
                    if field:
                        values[offset] = unicode(field)
                supplier = lot[Field.supplier_no].zfill(6)
                for module in ('posm', 'vnms'):
                    try:
                        supplier_id = values.supplier_id = oe_suppliers['%s-%s' % (module, supplier)].id
                        break
                    except LookupError:
                        pass
                else:
                    supplier_id = False
                if values.lot_no in oe_lots:
                    lot_id = oe_lots[values.lot_no].id
                    lots_model.write([lot_id], dict(values))
                else:
                    lot_id = lots_model.create(dict(values))
                values = get_records(OE, 'wholeherb_integration.product_lot', domain=[('id','=',lot_id)], max_qty=1)[0]
                lot_ids.add(lot_id)
                oe_lots[values.lot_no] = values
                oe_lots_by_id[lot_id] = values
            po_number = lot[Field.po_no]
            vessel = lot[Field.vessel]
            # this will have to wait :(
            # supplier = 
            po_key = po_number.lower()
            values = PropertyDict(purchase_order=unicode(po_number), vessel=unicode(vessel), supplier_id=supplier_id)
            if po_key in oe_purchases:
                purchase_order = oe_purchases[po_key]
                po_id = purchase_order.id
                lot_ids |= set(purchase_order.lot_ids)
                values.lot_ids = [(6, 0, list(lot_ids))]
                po_model.write([po_id], dict(values))
            else:
                values.lot_ids = [(6, 0, list(lot_ids))]
                po_id = po_model.create(dict(values))
            values = get_records(OE, 'wholeherb_integration.purchase_order', domain=[('id','=',po_id)], max_qty=1)[0]
            oe_purchases[po_key] = values
            oe_purchases_by_id[po_id] = values

@Command(
    )
def sample_lots(file_name):
    """Imports a file into product.lots

    example file name: Purchasing_Database_Table1.dbf

    """
    class Field(IntEnum):
        item_desc = 2
        lot = 3
    print 'connecting to OE...'
    OE = connect()
    lots_model = OE.conn.get_model('wholeherb_integration.product_lot')
    print 'getting Product records (this will a bit)...'
    oe_products = PropertyDict()
    for item in get_records(
            OE,
            model='product.product',
            fields=['id', 'xml_id', 'name', 'default_code'],
            ):
        key = item.xml_id or item.default_code
        if not key:
            print item
            continue
        oe_products[key] = item
    lots = Table(file_name)
    print 'processing %s...' % file_name
    pb = ProgressBar(len(lots)-1)
    for rec in dbf.Templates(lots, start=1):
        pb.tick()
        for fld in Field:
            rec[fld] = rec[fld].strip('"\'')
        lot_no = get_lot_no(rec[Field.lot])
        if not lot_no:
            continue
        item_code, desc = get_item_desc(rec[Field.item_desc])
        if not item_code:
            continue
        values = PropertyDict()
        try:
            values.product_id = oe_products[item_code].id
        except KeyError:
            continue
        values.lot_no = unicode(lot_no)
        lots_model.create(dict(values))

@Command(
        )
def sample_memo_lots(file_name):
    """
    Import a file into wholeherb_integration.sample_memo

    example file name: Sample_memo_db_Sample_Samples_Requested.dbf
    """
    class Field(IntEnum):
        order_id = 0
        item_desc = 2
        lot_no = 3
    print 'connecting to OE...'
    OE = connect()
    lot_model = OE.conn.get_model('wholeherb_integration.product_lot')
    print 'getting Product Lot records...'
    oe_lots = PropertyDict((r.lot_no, r) for r in get_records(lot_model))
    sample_model = OE.conn.get_model('wholeherb_integration.sample_memo')
    print 'getting Sample Memo Lot records...'
    oe_sample = PropertyDict((r.order_num, r) for r in get_records(sample_model))
    print 'getting Product records (this will take a bit)...'
    oe_products = PropertyDict()
    for item in get_records(
            OE,
            model='product.product',
            fields=['id', 'xml_id', 'name', 'default_code'],
            ):
        key = item.xml_id or item.default_code
        if not key:
            continue
        oe_products[key] = item
    table = Table(file_name)
    with table:
        def index(rec):
            if isinstance(rec, dbf.Record) and dbf.recno(rec) == 0:
                return dbf.DoNotIndex
            lot_no = get_lot_no(rec[Field.lot_no])
            if not lot_no:
                return dbf.DoNotIndex
            return rec[Field.order_id], lot_no
        order = table.create_index(index)
        print 'processing %s...' % file_name
        pb = ProgressBar(len(order))
        for order_num, lots in groupby(dbf.Templates(order), index):
            lot_ids = set()
            for rec in lots:
                pb.tick()
                for fld in Field:
                    rec[fld] = rec[fld].strip('"\'')
                lot_no = get_lot_no(rec[Field.lot_no])
                item_code, desc = get_item_desc(rec[Field.item_desc])
                # check for existing lot
                if lot_no in oe_lots:
                    lot_id = oe_lots[lot_no].id
                else:
                    if not item_code or item_code not in oe_products:
                        # no lot number, no item code -- skip record
                        continue
                    product_id = oe_products[item_code].id
                    lot_id = lot_model.create(dict(lot_no=lot_no, product_id=product_id))
                    lot_rec = get_records(lot_model, ids=lot_id, fields=['lot_no', 'product_id'])
                    oe_lots[lot_id] = lot_rec
                lot_ids.add(lot_id)
            values = PropertyDict()
            values.order_num = order_num = unicode(rec[Field.order_id])
            values.lot_ids = [(6, 0, list(lot_ids))]
            if order_num not in oe_sample:
                order_id = sample_model.create(dict(values))
                order_rec = get_records(sample_model, ids=order_id, fields=['id','lot_ids','order_num'])
                oe_sample[order_num] = order_rec
            else:
                order_rec = oe_sample[order_num]
                for id in order_rec.lot_ids:
                    lot_ids.add(id)
                values.lot_ids = [(6, 0, list(lot_ids))]
                sample_model.write([order_rec.id], dict(values))

@Command(
        )
def sample_memo_orders(file_name):
    """
    Import a file into wholeherb_integration.sample_memo

    exmaple file name: Sample_memo_db_Sample_Memo.dbf
    """
    class Field(IntEnum):
        order_id = 0
        employee_name = 2
        order_date = 3
        customer_id = 5
        ship_name = 6
        ship_address = 7
        ship_city = 8
        ship_state = 9
        ship_zip = 10
        ship_country = 11
        ship_contact = 12
        ship_phone = 13
        ship_date = 14
        shipping_method = 16
        comments1 = 17
        comments2 = 18
        comments3 = 19
    print 'connecting to OE...'
    OE = connect()
    OE.country = PropertyDict((r.name.lower(), r) for r in get_records(OE, 'res.country'))
    print 'getting Sample Memo Lot records...'
    sample_model = OE.sample = OE.conn.get_model('wholeherb_integration.sample_memo')
    oe_sample = OE.sample_data = PropertyDict((r.order_num, r) for r in get_records(sample_model))
    print 'getting Shipping Methods...'
    shipping_model = OE.shipping= OE.conn.get_model('wholeherb_integration.shipping_method')
    oe_shipping = OE.shipping_data = PropertyDict((r.name, r.id) for r in get_records(shipping_model))
    print 'getting sales reps...'
    partner_model = OE.partner = OE.conn.get_model('res.partner')
    oe_sales_reps = PropertyDict((r.name, r) for r in get_records(
            partner_model,
            domain=[('customer','=',False),('supplier','=',False)],
            fields=['id', 'name'],
            ))
    print 'getting customers and vendors...'
    oe_customer = OE.partner_data = PropertyDict()
    oe_suppliers = PropertyDict(default=list)
    for rec in get_records(
            partner_model,
            domain=[('xml_id','!=','')],
            fields=['id', 'xml_id', 'module', 'name', 'child_ids'],
            ):
        if rec.module == 'csms':
            oe_customer[rec.xml_id] = rec
        else:
            entry = oe_suppliers[rec.xml_id]
            entry.append(rec)
            entry.sort()
    table = Table(file_name)
    with table:
        def index(rec):
            if isinstance(rec, dbf.Record) and dbf.recno(rec) == 0:
                return dbf.DoNotIndex
            if not rec[Field.order_id]:
                return dbf.DoNotIndex
            return rec[Field.order_id]
        order = table.create_index(index)
        print 'processing %s...' % file_name
        pb = ProgressBar(len(order))
        for rec in dbf.Templates(order):
            pb.tick()
            for fld in Field:
                rec[fld] = rec[fld].strip('"\'\n\t ')
            values = PropertyDict()
            sales_person = rec[Field.employee_name]
            if sales_person in oe_sales_reps:
                values.employee_id = oe_sales_reps[sales_person].id
            values.order_date = (rec[Field.order_date]) or False
            customer_xmlid = rec[Field.customer_id]
            if customer_xmlid in oe_customer:
                customer = oe_customer[customer_xmlid]
                values.customer_id = customer.id
                contact_id = customer_contact(customer, *rec[Field.ship_name:Field.ship_date])
                if contact_id:
                    values.customer_contact_id = contact_id
            ship_date = rec[Field.ship_date].split(' ', 1)[0]
            if ship_date:
                values.ship_date = ship_date
            shipping_method = rec[Field.shipping_method]
            if shipping_method:
                if shipping_method not in oe_shipping:
                    sm_id = shipping_model.create(dict(name=shipping_method))
                    oe_shipping[shipping_method] = sm_id
                values.shipping_id = oe_shipping[shipping_method]
            comment = u'%-11s%-30s%-62s' % (rec[Field.comments1], rec[Field.comments2], rec[Field.comments3])
            comment = comment.strip('"').replace('\\n', '\n').strip()
            values.comments = comment
            order_num = rec[Field.order_id]
            if order_num not in oe_sample:
                values.order_num = order_num
                order_id = sample_model.create(dict(values))
                order_rec = get_records(
                        sample_model,
                        ids=order_id,
                        fields=['employee_id', 'order_date', 'customer_id', 'ship_date', 'comments'],
                        )
                oe_sample[order_num] = order_rec
            else:
                order_rec = oe_sample[order_num]
                sample_model.write(order_rec.id, dict(values))
    print 'done.'


if __name__ == '__main__':
    Run()
